name: Real World App CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Number of commits to fetch. 0 indicates all history for all branches and tags.  # Default: 1 - MIAŁEM TO NA KURSIE GOSCIU UZYWAŁ ALE CZY TO NIE JEST OVERKILL ??
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.1.2
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        working-directory: ./front
        run: pnpm install
      - name: Test
        working-directory: ./front
        run: pnpm run test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Number of commits to fetch. 0 indicates all history for all branches and tags.  # Default: 1 - MIAŁEM TO NA KURSIE GOSCIU UZYWAŁ ALE CZY TO NIE JEST OVERKILL ??
      - name: Setup
        uses: pnpm/action-setup@v2
        with:
          version: 7.1.2
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install dependencies
        working-directory: ./front
        run: pnpm install
      - name: Build
        working-directory: ./front
        run: pnpm run build
      - name: Copy index.html
        working-directory: ./front
        run: cp ./public/index.html ./public/build/index.html
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: conduit-build
          path: ./public/build
  publish:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: conduit-build
          path: ./build
      - name: Publish
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./build"
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
